# deafult settings for the theme
title: Hosted Demo-Changelog power by ChangelogHQ
subtitle: Check out the latest product updates below.
company: ChangelogHQ
logo: /assets/images/logo.png

# color configurtion for the theme
colors:   
  body-bg: "#fbfbfb" 
  header-bg: "#242e3a"
  header-ft: "#fff"
  post-bg: "#fff"
  post-ft: "#3d4852"

# default configuration for SCSS
sass:
  style: compressed 

# activate the needed plugins
plugins: 
  - jekyll-paginate

# Default configuration for pagination
paginate: 10
paginate_path: "/posts/:num/"

